DefaultPathForProjects: D:/SyncProfileProjects/Projects
MetaDataPath: config/
SyncInterval: 300
APIConfigs:
  ClientId: "h4GAKbCmY3BL1kAfIo2Gvfu9glp4KLvj"
  ClientSecret: "SEU_CLIENT_SECRET"
  EnterpriseId: "SEU_ENTERPRISE_ID"
  JwtPrivateKey: "|
    -----BEGIN PRIVATE KEY-----
    SUA_CHAVE_PRIVADA_AQUI
    -----END PRIVATE KEY-----"
  JwtPrivateKeyPassword: "SENHA_DA_CHAVE"
  JwtPublicKeyId: "ID_DA_CHAVE_PUBLICA"
