DefaultPathForProjects: D:/SyncProfileProjects/Projects
MetaDataPath: config/
SyncInterval: 300
APIConfigs:
  ClientId: "TI9GRLgFzZlRvqrIsixhhAp4Z9bsow1O"
  ClientSecret: "SEU_CLIENT_SECRET"
  EnterpriseId: "SEU_ENTERPRISE_ID"
  JwtPrivateKey: |
    -----BEGIN PRIVATE KEY-----
    SUA_CHAVE_PRIVADA_AQUI
    -----END PRIVATE KEY-----
  JwtPrivateKeyPassword: "SENHA_DA_CHAVE"
  JwtPublicKeyId: "ID_DA_CHAVE_PUBLICA"
