LocalProjects:
  NomeProjeto1:
    Name: Nome Teste 1
    DateTime: 2010-10-10T20:00:00.0000000
    Device: DeviceName
    Status: 0
  NomeProjeto2:
    Name: Nome Teste 2
    DateTime: 2012-10-10T20:00:00.0000000
    Device: DeviceNames
    Status: 1
